logging:
  level: INFO
  loggers:
    mx.jhcue: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: endimujt
  password: Jv4bpbaxY1MFfU8wCqaxMUeaN67jIzlc
  url: jdbc:postgresql://babar.elephantsql.com:5432/endimujt
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
  initialSize: 1
  minSize: 1
  maxSize: 5
