logging:
  level: INFO
  loggers:
    mx.jhcue: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: sgtbbzhz
  password: fyiYCBt5SSsdvgJO7WwP66oRepEX21Cm
  url: postgres://sgtbbzhz:fyiYCBt5SSsdvgJO7WwP66oRepEX21Cm@babar.elephantsql.com:5432/sgtbbzhz
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
