logging:
  level: INFO
  loggers:
    mx.jhcue: DEBUG

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: hlgm

  # the password
  password: P1xV4b3s+0

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/hlgm

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
